config/routes.rb
Rails.application.routes.draw do
  resources :links

  resources :directorios

  get 'welcome/index'

  devise_for :users

  root 'welcome#index'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

end

app/models/directorio.rb
class Directorio < ActiveRecord::Base
  belongs_to :user
  has_many:links, dependent: :destroy
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :directorio
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many:directorios, dependent: :destroy

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	       :recoverable, :rememberable, :trackable, :validatable

	#validaciones de campos.
	validates :rut, length: { in: 8..12 , message: "between 8 and 12 character minimum"}
	validates :rut, uniqueness: {case_sensitive: false ,message: "registered"}
	validates :nombre, :presence => {:message => "can't be blank"}
 	validates :apellidos, :presence => {:message => "can't be blank"}
 	validates :email, :presence => {:message => "can't be blank"}
 	validates :email, uniqueness: {case_sensitive: false}
 	validates :username, :presence => {:message => "can't be blank"}
 	validates :username, uniqueness: {case_sensitive: false}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:rut, :nombre, :apellidos, :username, :email, :password) }
            devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:rut, :nombre, :apellidos, :username, :email, :password, :current_password) }
        end
end

app/controllers/directorios_controller.rb
class DirectoriosController < ApplicationController
  before_action :set_directorio, only: [:show, :edit, :update, :destroy]

  # GET /directorios
  # GET /directorios.json
  def index
    @directorios = Directorio.all
  end

  # GET /directorios/1
  # GET /directorios/1.json
  def show
  end

  # GET /directorios/new
  def new
    @directorio = Directorio.new
  end

  # GET /directorios/1/edit
  def edit
  end

  # POST /directorios
  # POST /directorios.json
  def create
    @directorio = Directorio.new(directorio_params)

    respond_to do |format|
      if @directorio.save
        format.html { redirect_to @directorio, notice: 'Directorio was successfully created.' }
        format.json { render :show, status: :created, location: @directorio }
      else
        format.html { render :new }
        format.json { render json: @directorio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directorios/1
  # PATCH/PUT /directorios/1.json
  def update
    respond_to do |format|
      if @directorio.update(directorio_params)
        format.html { redirect_to @directorio, notice: 'Directorio was successfully updated.' }
        format.json { render :show, status: :ok, location: @directorio }
      else
        format.html { render :edit }
        format.json { render json: @directorio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directorios/1
  # DELETE /directorios/1.json
  def destroy
    @directorio.destroy
    respond_to do |format|
      format.html { redirect_to directorios_url, notice: 'Directorio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_directorio
      @directorio = Directorio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def directorio_params
      params.require(:directorio).permit(:user_id, :nombre, :descripcion, :area, :telefono, :celular, :direccion, :comuna, :ciudad, :region, :categoria, :subcategoria, :estado, :ruta)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:directorio_id, :tipo, :url)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directorios_helper.rb
module DirectoriosHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/directorios/_form.html.erb
<%= form_for(@directorio) do |f| %>
  <% if @directorio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@directorio.errors.count, "error") %> prohibited this directorio from being saved:</h2>

      <ul>
      <% @directorio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre, autofocus: true, autocomplete: "off" %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion, autocomplete: "off" %>
  </div>
  <div class="field">
    <%= f.label :area %><br>
    <%= f.number_field :area, autocomplete: "off" %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.number_field :telefono, autocomplete: "off" %>
  </div>
  <div class="field">
    <%= f.label :celular %><br>
    <%= f.number_field :celular, autocomplete: "off" %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion, autocomplete: "off" %>
  </div>
  <div class="field">
    <%= f.label :comuna %><br>
    <%= f.text_field :comuna, autocomplete: "off" %>
  </div>
  <div class="field">
    <%= f.label :ciudad %><br>
    <%= f.text_field :ciudad, autocomplete: "off" %>
  </div>
  <div class="field">
    <%= f.label :region %><br>
    <%= f.text_field :region, autocomplete: "off" %>
  </div>
  <div class="field">
    <%= f.label :categoria %><br>
    <%= f.text_field :categoria, autocomplete: "off" %>
  </div>
  <div class="field">
    <%= f.label :subcategoria %><br>
    <%= f.text_field :subcategoria, autocomplete: "off" %>
  </div>
  <div class="field">
    <%= f.label :estado %><br>
    <%= f.text_field :estado, autocomplete: "off" %>
  </div>
  <div class="field">
    <%= f.label :ruta %><br>
    <%= f.text_field :ruta, autocomplete: "off" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/directorios/edit.html.erb
<h1>Editing Directorio</h1>

<%= render 'form' %>

<%= link_to 'Show', @directorio %> |
<%= link_to 'Back', directorios_path %>

app/views/directorios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Directorios</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Area</th>
      <th>Telefono</th>
      <th>Celular</th>
      <th>Direccion</th>
      <th>Comuna</th>
      <th>Ciudad</th>
      <th>Region</th>
      <th>Categoria</th>
      <th>Subcategoria</th>
      <th>Estado</th>
      <th>Ruta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @directorios.each do |directorio| %>
      <tr>
        <td><%= directorio.user %></td>
        <td><%= directorio.nombre %></td>
        <td><%= directorio.descripcion %></td>
        <td><%= directorio.area %></td>
        <td><%= directorio.telefono %></td>
        <td><%= directorio.celular %></td>
        <td><%= directorio.direccion %></td>
        <td><%= directorio.comuna %></td>
        <td><%= directorio.ciudad %></td>
        <td><%= directorio.region %></td>
        <td><%= directorio.categoria %></td>
        <td><%= directorio.subcategoria %></td>
        <td><%= directorio.estado %></td>
        <td><%= directorio.ruta %></td>
        <td><%= link_to 'Show', directorio %></td>
        <td><%= link_to 'Edit', edit_directorio_path(directorio) %></td>
        <td><%= link_to 'Destroy', directorio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Directorio', new_directorio_path %>

app/views/directorios/new.html.erb
<h1>New Directorio</h1>

<%= render 'form' %>

<%= link_to 'Back', directorios_path %>

app/views/directorios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @directorio.user %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @directorio.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @directorio.descripcion %>
</p>

<p>
  <strong>Area:</strong>
  <%= @directorio.area %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @directorio.telefono %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @directorio.celular %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @directorio.direccion %>
</p>

<p>
  <strong>Comuna:</strong>
  <%= @directorio.comuna %>
</p>

<p>
  <strong>Ciudad:</strong>
  <%= @directorio.ciudad %>
</p>

<p>
  <strong>Region:</strong>
  <%= @directorio.region %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @directorio.categoria %>
</p>

<p>
  <strong>Subcategoria:</strong>
  <%= @directorio.subcategoria %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @directorio.estado %>
</p>

<p>
  <strong>Ruta:</strong>
  <%= @directorio.ruta %>
</p>

<%= link_to 'Edit', edit_directorio_path(@directorio) %> |
<%= link_to 'Back', directorios_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BaseDevise</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :directorio_id %><br>
    <%= f.text_field :directorio_id %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo, autofocus: true,  autocomplete: "off" %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url, autocomplete: "off" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Links</h1>

<table>
  <thead>
    <tr>
      <th>Directorio</th>
      <th>Tipo</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.directorio %></td>
        <td><%= link.tipo %></td>
        <td><%= link.url %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Directorio:</strong>
  <%= @link.directorio %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @link.tipo %>
</p>

<p>
  <strong>Url:</strong>
  <%= @link.url %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
	<p>Bienvenido <%= current_user.email %></p>
	<%= link_to ('sign_out') ,destroy_user_session_path, method: :delete %>
<%else%>
	<%=link_to "Register", new_user_registration_path %>
	<p>Si ya tienes una cuenta: <%=link_to "Logueate", new_user_session_path%></p>
<%end%>